
name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  

jobs:
  lint: #id of the job
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Run lint 
        run: |
          npm run lint 
      - name: Run prettier
        run: |
          npm run format

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Type check 
        run: |
          npm run type-check
        with:
          node-version: ${{ matrix.node }}

  
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Run test 
        run: |
          npm run test
        with:
          node-version: ${{ matrix.node }}
        
  build:
    needs: [unit-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Run build
        run: |
          npm start

  deploy:
    publish-gpr:
      needs: [build]
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node: [12.x, 14.x, 16.x, 18.x, 20.x]
      permissions:
        contents: read
        packages: write
      steps:
        - name: Checkout Commit
          uses: actions/checkout@v4
        - name: Setup Node.js with Custom Registry
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node }}
            registry-url: https://npm.pkg.github.com/
        - name: Install Dependencies
          run: |
            npm ci
        - name: Publish package to GitHub Package Registry
          run: |
            npm publish
          env:
            NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}


  
  
