# CI/CD workflow for testing, building, and deploying
# triggered automatically on push to main branch, pull request to main branch, or manually by a user
# overview: catch common errors, check for types mismatch, run unit tests -> build -> and deploy to Netlify
# job dependencies: build depends on unit-test, deploy depends on build

name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Change to the directory containing package.json
        run: |
          echo "before moving, Current Directory: $PWD"
          cd ..; 
          echo "move 1 up, Current Directory: $PWD"
          ls;
          echo "after moving to fluentify, Current Directory: $PWD";

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: |
          echo "before npm ci, Current Directory: $PWD"
          npm ci
      - name: Run lint
        run: |
          echo "before run lint, Current Directory: $PWD"
          npm run lint
      - name: Run prettier
        run: |
          echo "before format, Current Directory: $PWD"
          npm run format

  type-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Type check
        run: |
          npm run type-check
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Run test
        run: |
          npm run test

  build:
    needs: [unit-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Run build
        run: |
          npm run build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x, 18.x, 20.x]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          npm ci
      - name: Run build
        run: |
          npm run build
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: "./dist"
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: nfp_69NJsP72wxzg4MEdgG4Wus3WJBHDBz1c74e3 #UNIQUE TOKEN. KEEP PRIVATE!
          NETLIFY_SITE_ID: 47d3c9b0-1398-4aee-a266-f4ae6a4c95de #NETLIFY SITE ID

